export const DEMO_AUTH_USER = {
  id: "demo-admin",
  username: "admin",
  displayName: "Platform Admin",
  mustChangePassword: true,
  status: "PENDING_PASSWORD_RESET",
  roles: ["admin"] as const,
  permissions: [
    "audit:read",
    "command:approve",
    "command:create",
    "command:execute",
    "command:read",
    "role:manage",
    "server:read",
    "server:write",
    "storage:delete",
    "storage:manage-node",
    "storage:read",
    "storage:write",
    "user:manage",
    "user:read",
  ] as const,
};

export const DEMO_SERVERS = [
	{
		id: "srv_demo_hk_1",
		name: "hk-prod-1",
		host: "203.0.113.10",
		port: 22,
		username: "root",
		description: "香港生产节点，作为统一纳管演示入口。",
		tags: ["prod", "hk"],
		enabled: true,
		connectionType: "SSH_KEY",
		sshKeyId: null,
		password: null,
		createdAt: "2026-04-18T14:00:00.000Z",
		updatedAt: "2026-04-18T14:00:00.000Z",
		sshKey: { id: "ssh_demo_root", name: "prod-root-key", fingerprint: "SHA256:demo-prod-root" },
		storageNode: { id: "node_demo_media", name: "香港媒体库", driver: "SFTP", isDefault: false, basePath: "/data/media" },
		statusLabel: "已启用",
		connectionTypeLabel: "SSH 密钥",
		targetCount: 2,
		pendingCommandCount: 1,
		latestCommands: [
			{
				id: "cmd_demo_1",
				title: "Restart nginx",
				initiatedByType: "ASSISTANT",
				requestStatus: "PENDING_APPROVAL",
				targetStatus: "PENDING_APPROVAL",
				createdAt: "2026-04-18T14:00:00.000Z",
			},
		],
		connectionSummary: "root@203.0.113.10:22，使用 SSH 密钥 prod-root-key 连接",
	},
	{
		id: "srv_demo_sg_1",
		name: "sg-storage-1",
		host: "203.0.113.21",
		port: 22,
		username: "root",
		description: "新加坡存储节点，用于浏览器直连分发演示。",
		tags: ["storage", "sg"],
		enabled: true,
		connectionType: "SSH_KEY",
		sshKeyId: null,
		password: null,
		createdAt: "2026-04-18T15:00:00.000Z",
		updatedAt: "2026-04-18T15:00:00.000Z",
		sshKey: { id: "ssh_demo_root", name: "prod-root-key", fingerprint: "SHA256:demo-prod-root" },
		storageNode: null,
		statusLabel: "已启用",
		connectionTypeLabel: "SSH 密钥",
		targetCount: 1,
		pendingCommandCount: 0,
		latestCommands: [
			{
				id: "cmd_demo_2",
				title: "Check disk usage",
				initiatedByType: "USER",
				requestStatus: "COMPLETED",
				targetStatus: "COMPLETED",
				createdAt: "2026-04-18T15:00:00.000Z",
			},
		],
		connectionSummary: "root@203.0.113.21:22，使用 SSH 密钥 prod-root-key 连接",
	},
];

export const DEMO_STORAGE_OVERVIEW = {
  nodes: [
	{
		id: "node_demo_local",
		name: "主控本机",
		driver: "LOCAL",
		isDefault: true,
		basePath: "/srv/app/storage",
		serverId: null,
		server: null,
		connectionSummary: "本机存储：/srv/app/storage",
		directAccess: { mode: "managed-download", description: "本机文件由管理端直接提供受控下载与预览。", href: null },
		fileCount: 3,
	},
	{
		id: "node_demo_media",
		name: "香港媒体库",
		driver: "SFTP",
		isDefault: false,
		basePath: "/data/media",
		host: "203.0.113.11",
		port: 22,
		username: "root",
		serverId: null,
		server: null,
		connectionSummary: "SFTP 存储：root@203.0.113.11:22（绑定节点 hk-media-1），根目录 /data/media",
		directAccess: { mode: "managed-download", description: "远端文件经管理端 SFTP 代理中转下载（来自 203.0.113.11:22）。", href: "/api/storage/sftp-download?nodeId=node_demo_media&path=" },
		fileCount: 8,
	},
  ],
  entries: [
    {
      id: "file_demo_1",
      name: "demo.mp4",
      mimeType: "video/mp4",
      relativePath: "videos/demo.mp4",
      sizeLabel: "1024 B",
      localEditable: false,
      previewable: true,
      directAccess: { mode: "managed-download", description: "远端文件经管理端 SFTP 代理中转下载（来自 203.0.113.11:22）。", href: "/api/storage/sftp-download?nodeId=node_demo_media&path=videos%2Fdemo.mp4" },
      storageNode: { id: "node_demo_media", name: "香港媒体库", driver: "SFTP" },
      entryType: "FILE",
    },
    {
      id: "file_demo_2",
      name: "cover.jpg",
      mimeType: "image/jpeg",
      relativePath: "images/cover.jpg",
      sizeLabel: "512 B",
      localEditable: false,
      previewable: true,
      directAccess: { mode: "managed-download", description: "本机文件由管理端直接提供受控下载与预览。", href: "/api/storage/local?path=images%2Fcover.jpg" },
      storageNode: { id: "node_demo_local", name: "主控本机", driver: "LOCAL" },
      entryType: "FILE",
    },
  ],
  remoteDirectories: [
    { storageNodeId: "node_demo_media", storageNodeName: "香港媒体库", storageNodeDriver: "SFTP", path: "videos", name: "videos", itemCount: 1 },
    { storageNodeId: "node_demo_local", storageNodeName: "主控本机", storageNodeDriver: "LOCAL", path: "images", name: "images", itemCount: 1 },
  ],
  stats: {
    totalNodes: 2,
    defaultNodeName: "主控本机",
    localNodeCount: 1,
    sftpNodeCount: 1,
    totalEntries: 2,
    previewableEntries: 2,
    remoteDirectoryCount: 2,
  },
};

export const DEMO_COMMAND_REQUESTS: Array<{
  id: string; title: string; command: string; reason: string | null; status: string; approvalStateLabel: string; isAssistantInitiated: boolean; requester: { id: string; username: string; displayName: string | null }; targets: Array<{ id: string; status: string; server: { id: string; name: string; host: string; port: number } }>; latestApproval: null | { approved: boolean; approver: { displayName: string | null; username: string }; comment: string | null }; latestLog: { id: string; summary: string } | null;
}> = [
  {
    id: "cmd_demo_1",
    title: "Restart nginx",
    command: "systemctl restart nginx",
    reason: "Routine maintenance",
    status: "PENDING_APPROVAL",
    approvalStateLabel: "待审批",
    isAssistantInitiated: true,
    requester: { id: DEMO_AUTH_USER.id, username: DEMO_AUTH_USER.username, displayName: "管理员" },
    targets: [
      {
        id: "target_demo_1",
        status: "PENDING_APPROVAL",
        server: { id: "srv_demo_hk_1", name: "hk-prod-1", host: "203.0.113.10", port: 22 },
      },
    ],
    latestApproval: null,
    latestLog: { id: "log_demo_1", summary: "数据库暂不可用，当前展示为只读回退数据。" },
  },
  {
    id: "cmd_demo_2",
    title: "Check disk usage",
    command: "df -h",
    reason: "User self-service operation",
    status: "COMPLETED",
    approvalStateLabel: "已完成",
    isAssistantInitiated: false,
    requester: { id: DEMO_AUTH_USER.id, username: DEMO_AUTH_USER.username, displayName: "管理员" },
    targets: [
      {
        id: "target_demo_2",
        status: "COMPLETED",
        server: { id: "srv_demo_sg_1", name: "sg-storage-1", host: "203.0.113.21", port: 22 },
      },
    ],
    latestApproval: { approved: true, approver: { displayName: "管理员", username: "admin" }, comment: "演示通过" },
    latestLog: { id: "log_demo_2", summary: "用户站内自主操作可直接执行；此处为演示执行结果。" },
  },
] as const;
